/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.30
</auto-generated>
------------------------------------------------------------------------------ */

using ExternalWidgets.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace ExternalWidgets.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "Michael", Title = "Michael", SectionName = "SFAdvDevAug2022")]
	public class MichaelController : Controller, IPersonalizable
	{
		// GET: Michael
		public ActionResult Index()
		{
			var model = new MichaelModel();
			model.Message = this.Message;
			return View(model);
		}

		protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}