/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.30
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace ExternalWidgets.Mvc.Models
{
	public class MichaelModel
	{
		public string Message { get; set; }
	}
}